# Site settings
title: ChangeGeek
email: skotlov@gmail.com
description: >
  Sergey Kotlov's blog where I write about my experience working at the
  international network of businesses called Happy Melly, helping people
  be happy at work and visiting inspiring organisations around the world which
  care about happiness of their employees.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://changegeek.ru" # the base hostname & protocol for your site
twitter_username: skotlov
github_username:  sery0ga
paginate: 5
paginate_path: "/blog/page:num/"
permalink: /blog/:year/:month/:day/:title.html

# Build settings
markdown: kramdown
gems: [jekyll-paginate]